# Generated by Django 4.0.2 on 2022-03-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_parent_comment_password_comment_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savehistories', to='blog.article')),
            ],
        ),
    ]
